wordlist = <<HEREDOC
/admin1/
/admin2/
/admin3/
/admin4/
/admin5/
/kcfinder/upload.php
/adminbackup/
/admin.php
/4dmin.php
/admin.html
/admin.aspx
/login.php
/login.html
/login.aspx
/administrator/
/adminpanel/
/Admin_web/
/Admin_panel/
/Admin_panel/login.php
/Admin_panel/index.html
/Admin_panel/home.php
/Admin_login/
/Admin_login/login.php
/Admin_login.php
/admin_login.php
/admin_login/login.php
/admin_login/index.php
/Admin-web/
/Admin-panel/
/Admin-panel/login.php
/Admin-panel/index.html
/Admin-panel/home.php
/Admin-login/
/Admin-login/login.php
/Admin-login.php
/admin-login.php
/admin-login/login.php
/admin-login/index.php
/Adminweb/
/Adminpanel/
/Adminpanel/login.php
/Adminpanel/index.html
/Adminpanel/home.php
/Adminlogin/
/Adminlogin/login.php
/Adminlogin.php
/adminlogin.php
/adminlogin/login.php
/adminlogin/index.php
/pages/admin
/login/admin
/dashboard.php
/admin/Dashboard.php
/admin/add-banner.php
/admin/add-gallery.php
/admin/addgallery.php
/admin/add_gallery.php
/admin/home.php
/admin/welcome.php
/pages/admin/
/admin-login/
/adminweb/
/webadmin/
/4dmin/
/4dminweb/
/web4dmin/
/author/admin
/admin/admin.php
/admin/admin.html
/admin/adnin.aspx
/admin/login.php
/admin/login.html
/admin/login.aspx
/admin_dashboard/
/Admin/
/Admin/login.php
/Admin/login.html
/Admin/login.aspx
/administratorlogin/
/administratorLogin/
/administator/login.php
/administator/login.html
/administator/administrator.php
/administator/administrator.html
/panel-admin/
/sistemadmin/
/control-admin/
/control_admin/
/panel/
/cms/
/cmas/
/cms/login.php
/CMS/
/cmsAdmin/
/Cmsadmin/
/CMSadmin/
/cmspanel/
/cmsadmin/
/adminpage/
/adminpages/
/adminpage/admin.php
/adminpage/login.php
/adminpages/login.php
/adminpages/index.php
/admin-pages/
/admin-page/
/admin_pages/
/admin_page/
/AdminPage/
/AdminPages/
/admins/login/
/admins
/admin-control/
/admin_control/
/admin/
/wp-login.php
/controlcenter/login.php
/controlcenter/
/control-panel/
/control_panel/
/adm/
/adm/login-admin.php
/adm/login.php
/admincontrol/
/adminarea/
/admin_area/
/joomla/
/admincp/
/operator/
/sika/
/develop/
/ketua/
/redaktur/
/author/
/user/
/users/
/dinkesadmin/
/author/
/paneladmin/
/panellogin/
/cp-admin/
/master/
/master/index.php
/master/login.php
/operator/index.php
/sika/index.php
/develop/index.php
/ketua/index.php
/redaktur/index.php
/user/index.php
/users/index.php
/dinkesadmin/index.php
/retel/index.php
/author/index.php
/panel/index.php
/paneladmin/index.php
/panellogin/index.php
/redaksi/index.php
/cp-admin/index.php
/operator/login.php
/sika/login.php
/develop/login.php
/ketua/login.php
/redaktur/login.php
/terasadmin/
/terasadmin/index.php
/terasadmin/login.php
/rahasia/
/rahasia/index.php
/rahasia/admin.php
/rahasia/login.php
/dinkesadmin/
/dinkesadmin/login.php
/adminpmb/
/adminpmb/index.php
/adminpmb/login.php
/system/
/system/index.php
/system/login.php
/webadmin/index.php
/webadmin/login.php
/adminkec/
/adminkec/index.php
/adminkec/login.php
/admindesa/
/admindesa/index.php
/admindesa/login.php
/adminkota/
/adminkota/index.php
/adminkota/login.php
/admin123/
/server/
/server/manager/
/manager/
/admin123/index.php
/admin123/login.php
/backend/
/Login/Admin
/systemLogin.php
/systemlogin.php
/newadm/login.php
/newadm/
/assets/admin/
/asset/admin/
/superadmin/
/admin_jdi/
/phpmyadmin/
/backpanel/pages/
/backpanel/login.php
/backpanel/
/backpanel/login
/robots.txt
/admin-pro
/index.php/login
/index.php/login
/index.php/panel
//index.php/webadmin/
//index.php/webadmin/login
//index.php/admin
HEREDOC

require 'net/http'
print "Masukkan Web (with http/https) : "
url = URI.parse(gets.chomp)
web = Net::HTTP.new(url.host, url.port)
web.use_ssl = true unless url.port == 80

wordlist.each_line do |path|
	path.chomp!
	print "#{url.to_s}#{path} "
	if web.get(path).code == '200'
		puts " FOUND!"
		break
	else
		puts " Error"
	end
end